### PR TITLE
Add move code about red packet.

### PR DESCRIPTION
**Pull request by gguoss**

### CODE REVIEW

**Comment by villesundell** [comment]
Thank you for the contribution! Considering that this is part of ComingChat which is already included, adding this would make sense. Personally I would hope a `LICENSE` file, so the code would be officially open source: without a license no-one can legally use your code (my personal favorite is [`Apache 2.0`](https://github.com/move-language/move/blob/main/LICENSE) if you need help selecting one :wink:).

**Comment by gguoss** [comment]
> Thank you for the contribution! Considering that this is part of ComingChat which is already included, adding this would make sense. Personally I would hope a `LICENSE` file, so the code would be officially open source: without a license no-one can legally use your code (my personal favorite is [`Apache 2.0`](https://github.com/move-language/move/blob/main/LICENSE) if you need help selecting one 😉).

Thanks to your suggestion, we have added the Apache 2.0 open source license.

**Review by villesundell — APPROVED** [review]

**Comment by villesundell** [comment]
@gguoss Thank you for the fix :slightly_smiling_face: There is one thing I have been wondering, though: the code looks fine, but considering the deployer controls the whole contract (deposits to the contract, sending tokens to lucky addresses, and withdrawing to the beneficiary), why this smart contract is actually needed? :thinking: Would regular transfer scripts send by ComingChat do the same thing? (It would also be completely controlled by the account owner, as is the case with this smart contract)

Just asking out of curiosity: since the code looks fine, I think this can be added to the list.

**Comment by icodezjb** [comment]
Hi, @villesundell
With the launch of Aptos/Sui, we will deploy the red envelope automatic distribution algorithm to the aptos/sui network, but we need another oracle project like ChainLink on aptos/sui to help us implement it. It's early days, and we only open source the red envelope settlement code. The intelligent allocation algorithm on the chain will be open sourced later

**Pull request merged**
