### PR TITLE
Update 0L discord to slugs instead of invitation codes.

### PR DESCRIPTION
**Pull request by Foorgoo**
Update 0L discord to slugs instead of invitation codes

### CODE REVIEW

**Comment by villesundell** [comment]
@Foorgoo A great find, thanks again! :+1: However, we recently started requiring more descriptive commit messages because the log started to fill with generic `Update README.md` commits, which is the default commit message when using GitHub Web UI. Once the commit message is a bit more descriptive (you can use the PR title, that's very informative) I will merge this :+1:

**Review by uvd — APPROVED** [review]

**Comment by villesundell** [comment]
@Foorgoo The commit text is now descriptive (there is an extra ".md" in the end, though) :+1: However, the old commit is still there: instead of one commit, there are now three (original, merge commit and the new one). Depending of the tools at your disposal, there are a few options:
  * If have `git` tools, you could:
    * Discard the new commits with [`git reset`](https://stackoverflow.com/questions/5097456/throw-away-local-commits-in-git), and `amend` the original with `git commit README.md --amend` and force-push (`git push -f`) to to your `main`, **OR**
    * Make a new branch `main-2` forking from `MystenLabs:main` and then force-push (`git push -f`) to `Foorgoo:main` after making your new descriptive commit
  * If you are using GitHub Web UI, I am not aware of other ways than re-doing the change with another commit message

**Comment by Foorgoo** [comment]
> @Foorgoo The commit text is now descriptive (there is an extra ".md" in the end, though) 👍 However, the old commit is still there: instead of one commit, there are now three (original, merge commit and the new one). Depending of the tools at your disposal, there are a few options:
> 
> * If have `git` tools, you could:
>   
>   * Discard the new commits with [`git reset`](https://stackoverflow.com/questions/5097456/throw-away-local-commits-in-git), and `amend` the original with `git commit README.md --amend` and force-push (`git push -f`) to to your `main`, **OR**
>   * Make a new branch `main-2` forking from `MystenLabs:main` and then force-push (`git push -f`) to `Foorgoo:main` after making your new descriptive commit
> * If you are using GitHub Web UI, I am not aware of other ways than re-doing the change with another commit message

I'm very sorry, I'll revise it again, thank you for your patience to remind

**Comment by villesundell** [comment]
@Foorgoo Thanks for fixing that! :+1: There is still the extra `.md` in the end, that might be confusing to reader of the commit

**Comment by villesundell** [comment]
@Foorgoo If you don't mind, I could modify the commit (it still has the `.md` suffix, which is confusing) and commit it directly to `main`. You would be listed as the author, and I would be listed as the committer.

**Pull request merged**
