### PR TITLE
feat: add wallet adapter & wallet kit section, append Suiet wallet

### PR DESCRIPTION
**Pull request by fredliang44**

### CODE REVIEW

**Comment by fredliang44** [comment]
@villesundell Currently our chrome extension is in private beta(also tagged in the README), so the link will not available by the bot, but for beta testers the link is available.

That's the reason cause link check bot report error, it's as expected

**Comment by villesundell** [comment]
@fredliang44 Thanks for the contribution! :+1:  Although it passes lint (:tada:), there are a few issues:
  * All the new entries should be added to the bottom of each category. Please see the [contribution requirements](https://github.com/MystenLabs/awesome-move/blob/main/CONTRIBUTING.md).
  * The description should not read like an advertisement. Every project is "the best" and "well designed" in their own opinion. Design choices themselves could be written out, though.
  * The public webstore link should be added when available, instead of the private one that user's can't use.
  * [`wallet-adapter`](https://github.com/suiet/wallet-adapter) does not have license information, making it effectively non-open source.
  * [`wallet-kit`](https://github.com/suiet/wallet-kit) does not have license information, making it effectively non-open source.

But there are also a lot of good things, such as:
  * Very descriptive commit message.
  * Suiet wallet itself is a good addition.
  * Wallet adapter section is a good idea in my opinion, since that's a thing in the Sui universe.
  * Style is followed, and passes lint.

And a question:
  * Is the `wallet-kit` designed to be a UI for wallet adapter(s)? Or is it basically an adapter?

Once the issues are fixed ([guide on editing PRs](https://github.com/RichardLitt/knowledge/blob/master/github/amending-a-commit-guide.md)), I am for merging this :+1: (Don't worry about the broken link check, it's flaky and will be fixed in the future)

**Comment by fredliang44** [comment]
@villesundell Appreciate for your detailed description. All problems you've mentioned are fixed now, please take a look.

As for your question about the wallet kit, you can regard the Wallet Kit as a package have customizable UI with a set of unified of API for Dapps. They can connect all wallets on Sui with a singe package.

**Comment by villesundell** [comment]
@fredliang44 Thank you for fixing these issues so quickly! Merging this :+1:

**Pull request merged**
