### PR TITLE
Add OmniBTC Bridge

### PR DESCRIPTION
**Pull request by icodezjb**

### CODE REVIEW

**Comment by villesundell** [comment]
@icodezjb Thank you for the contribution! However the description must end with `.` (that's why it's failing lint). Easiest way to fix this is to amend the commit (which is descriptive, thank you for that too!), and force-pushing it to your branch.

We used to have an open OmniBTC PR (#22). I'll leave the final call on merging this to @sblackshear

**Review by villesundell — APPROVED** [review]
Good job! :+1:

**Comment by icodezjb** [comment]
@villesundell 
Why did the ci fail and what should I do?

**Comment by villesundell** [comment]
@icodezjb Nothing: linting (the most important part) is successful. Broken link check is flaky, failing occasionally.

**Comment by villesundell** [comment]
@sblackshear This looks good to me, if you don't have any objections (per #22 ), I am ready to merge this :+1:

**Comment by villesundell** [comment]
Going to merge this :+1: Thank you for the contribution @gguoss, and sorry for the delay :slightly_smiling_face:

**Pull request merged**
