### PR TITLE
Add MoveDID

### PR DESCRIPTION
**Pull request by hqwangningbo**
**Thank you for making this list awesome! Please make sure that your addition follows the format `[project_name](link) - Description.` and other [contribution requirements](https://github.com/MystenLabs/awesome-move/blob/main/CONTRIBUTING.md#contributing) such as the `Add project_name` commit format.**

### CODE REVIEW

**Comment by villesundell** [comment]
Thank you for the contribution @hqwangningbo :+1: The project itself suits well to the list. However, license is not specified (making it essentially closed source), once specified ([GitHub instructions](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)), I will merge this :slightly_smiling_face:

**Comment by hqwangningbo** [comment]
> Thank you for the contribution @hqwangningbo 👍 The project itself suits well to the list. However, license is not specified (making it essentially closed source), once specified ([GitHub instructions](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)), I will merge this 🙂

Already added

**Comment by hqwangningbo** [comment]
@villesundell Can you help to follow up, thanks

**Comment by villesundell** [comment]
@hqwangningbo Thank you for reacting so quickly, and I am sorry for reacting so slowly: I missed this. Will merge :+1: (A great license choice, btw!)

**Pull request merged**
